### ISSUE TITLE
dupl things two switch/case clauses are the same when they differ in variable type creation. Mention the actual behaviour in README.

### ISSUE THREAD

**Issue by oryband** [mibk/dupl#10]
Consider this go code:
```go
switch raw.VersionField {
// v1.Version and v2.Version are just strings aliases.
case v1.Version:
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.UseNumber()
	var m v1.QueueMessage
	// some more code
case v2.Version:
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.UseNumber()
	var m v2.QueueMessage
	// some more code, similar to the previous clause.
}
```
Running `dupl` on this returns:
```go
duplicate of ./api.go:119-150 (dupl) // Lines belong to the second clase
duplicate of ./api.go:87-118 (dupl)  // Lines belong to the first clause
```
There are two issues here:
1. These two cases aren't the same, and differ by the `var m v1.QueueMessage` line.
2. Presuming that they are the same, they're linking each other in the error message. I guess the link should be one way, from the duplicate (the second clause, the with `v2`) to the first.

**Comment by mibk** [comment]
This is just an issue related to the method dupl uses for clone detection. It's a "false positive" match. The algorithm works only with token types, not their values. From certain angle I would say it is a duplicate because if both cases are that similar, their behaviour could be probably abstracted to an interface.

Ad 2. issue: I think it works as expected. You can check #2 where we have discussed the desired output format.

Did I miss something?

**Comment by oryband** [comment]
actually, this switch case is for initializing different structs which implement the same interface, so there isn't any further abstraction i can do in this case. if you say this is a FP than ok, but I think the chance for FPs should be mentioned in the README or something.

**Comment by oryband** [comment]
it also means i should unfortunately take this tool with a grain of salt, since not all comments are TP :\

**Comment by mibk** [comment]
That's just the way it is. You are right it should be more emphasized in README. It only contains one sentence about it (`It ignores values of AST nodes, it cares just about the types.`) so far. The reason is English is my second language. So I find it quite uncomfortable to write long passages of text.

dupl is a tool, it is not a source of truth. It should provide a user information about possible clones that would have been otherwise missed by the user.

**Comment by shurcooL** [comment]
Yeah, `dupl` is not a tool whose output can be run in CI and non-zero output can be considered a failure, the way, for example, `vet` is. It's more like `golint`, its output are hints, some of which may be helpful, some others may be noise.

On another note, in your original code, couldn't you factor out:

```Go
dec := json.NewDecoder(bytes.NewReader(b))
dec.UseNumber()
```

It seems that part is duplicated without necessity. It case it happens to lead to more readable, better code to factor it out, then `dupl` has been helpful even in this relatively false positive-y case.

**Comment by oryband** [comment]
I agree, and maybe you should quote from here in the README.

**Comment by oryband** [comment]
thanks for the quick response :)
hurray for awesome maintainers :+1:

**Comment by mibk** [comment]
You're welcome :-)
